[package]
name = "fact-extractor"
version = "0.1.0"
edition = "2024"

[dependencies]
color-eyre = { workspace = true }
dotenvy = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
tokio = { workspace = true }
sqlx = { workspace = true }
ormlite = { workspace = true }
unidb = { workspace = true }
reqwest = "0.13.3"
base64 = "0.22.1"
chrono = "0.4.44"
uuid = { version = "1.23.1", features = ["v8"] }
sha2 = "0.11"
hex = "0.4.3"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
async-openai = { version = "0.38", features = [
    "chat-completion",
    "native-tls",
] }
